version: '3.8'

services:
  db:
    image: gkontsevik/trud-postgis:1.0.0  # ← this is YOUR pushed image w/ trud preloaded
    container_name: trud-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trud
    ports:
      - "5432:5432"
    restart: always
    
  planter:
    build: ./
    image: gkontsevik/planter:1.0.1
    volumes:
      - ./:/usr/api/
    platform: linux/amd64
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/trud
    depends_on:
      - db