"""added specialists as a separate table related to project

Revision ID: 15dba6f62a24
Revises: a1ed026bf506
Create Date: 2024-11-30 20:57:05.041303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '15dba6f62a24'
down_revision: Union[str, None] = 'a1ed026bf506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
