"""added group_name for layer

Revision ID: 1f8c12285d69
Revises: 5e35be8fdeb1
Create Date: 2024-12-18 17:02:46.504019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '1f8c12285d69'
down_revision: Union[str, None] = '5e35be8fdeb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layers', sa.Column('group_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layers', 'group_name')
    # ### end Alembic commands ###
