"""added group_id for layers

Revision ID: 2414551de597
Revises: b3ce2e11e622
Create Date: 2024-12-19 18:26:51.996850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '2414551de597'
down_revision: Union[str, None] = 'b3ce2e11e622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('layers', 'geometry',
               existing_type=geoalchemy2.types.Geometry(from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               nullable=False)
    op.drop_constraint('layers_project_id_fkey', 'layers', type_='foreignkey')
    op.create_foreign_key(None, 'layers', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('specialists', 'count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('specialists', 'count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'layers', type_='foreignkey')
    op.create_foreign_key('layers_project_id_fkey', 'layers', 'projects', ['project_id'], ['id'])
    op.alter_column('layers', 'geometry',
               existing_type=geoalchemy2.types.Geometry(from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               nullable=True)
    # ### end Alembic commands ###
