"""added bool metric col and float metric col

Revision ID: 4323cd3a5b3a
Revises: 6b7109a03205
Create Date: 2024-12-05 04:20:46.028449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '4323cd3a5b3a'
down_revision: Union[str, None] = '6b7109a03205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('metric_bool', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('metric_float', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'metric_float')
    op.drop_column('projects', 'metric_bool')
    # ### end Alembic commands ###
