"""added props style for layers

Revision ID: 5e35be8fdeb1
Revises: b00602d166b9
Create Date: 2024-12-18 00:22:20.448137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '5e35be8fdeb1'
down_revision: Union[str, None] = 'b00602d166b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layers', sa.Column('style', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layers', 'style')
    # ### end Alembic commands ###
