"""added group_id for layers

Revision ID: 697bb34eb5dc
Revises: fb094180fe68
Create Date: 2024-12-19 22:54:49.739233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '697bb34eb5dc'
down_revision: Union[str, None] = 'fb094180fe68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layers', sa.Column('city_category', sa.String(), nullable=True))
    op.add_column('layers', sa.Column('factories_total', sa.Integer(), nullable=True))
    op.add_column('layers', sa.Column('harsh_climate', sa.Integer(), nullable=True))
    op.add_column('layers', sa.Column('migrations_from_each_city', sa.Float(), nullable=True))
    op.add_column('layers', sa.Column('region_city', sa.String(), nullable=True))
    op.add_column('layers', sa.Column('ueqi_citywide_space', sa.Integer(), nullable=True))
    op.add_column('layers', sa.Column('ueqi_green_spaces', sa.Integer(), nullable=True))
    op.add_column('layers', sa.Column('ueqi_public_and_business_infrastructure', sa.Integer(), nullable=True))
    op.add_column('layers', sa.Column('ueqi_residential', sa.Integer(), nullable=True))
    op.add_column('layers', sa.Column('ueqi_social_and_leisure_infrastructure', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layers', 'ueqi_social_and_leisure_infrastructure')
    op.drop_column('layers', 'ueqi_residential')
    op.drop_column('layers', 'ueqi_public_and_business_infrastructure')
    op.drop_column('layers', 'ueqi_green_spaces')
    op.drop_column('layers', 'ueqi_citywide_space')
    op.drop_column('layers', 'region_city')
    op.drop_column('layers', 'migrations_from_each_city')
    op.drop_column('layers', 'harsh_climate')
    op.drop_column('layers', 'factories_total')
    op.drop_column('layers', 'city_category')
    # ### end Alembic commands ###
