"""added group_id for layers

Revision ID: 6b25df109b2f
Revises: 7bb82e5cb57a
Create Date: 2024-12-19 16:31:48.670955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b25df109b2f'
down_revision: Union[str, None] = '7bb82e5cb57a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('layers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('layers', 'geometry',
               existing_type=geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
               type_=geoalchemy2.types.Geometry(from_text='ST_GeomFromEWKT', name='geometry'),
               nullable=True)
    op.drop_index('ix_layers_id', table_name='layers')
    op.drop_constraint('layers_project_id_fkey', 'layers', type_='foreignkey')
    op.create_foreign_key(None, 'layers', 'projects', ['project_id'], ['id'])
    op.drop_column('layers', 'line_width')
    op.drop_column('layers', 'color')
    op.drop_column('layers', 'created_at')
    op.drop_column('layers', 'fill_opacity')
    op.drop_column('layers', 'updated_at')
    op.drop_column('layers', 'group_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layers', sa.Column('group_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('layers', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('layers', sa.Column('fill_opacity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('layers', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('layers', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('layers', sa.Column('line_width', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'layers', type_='foreignkey')
    op.create_foreign_key('layers_project_id_fkey', 'layers', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_layers_id', 'layers', ['id'], unique=False)
    op.alter_column('layers', 'geometry',
               existing_type=geoalchemy2.types.Geometry(from_text='ST_GeomFromEWKT', name='geometry'),
               type_=geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
               nullable=False)
    op.alter_column('layers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
