"""removed enums to models

Revision ID: 6b7109a03205
Revises: ab05e3f83ca2
Create Date: 2024-12-05 04:03:32.425897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '6b7109a03205'
down_revision: Union[str, None] = 'ab05e3f83ca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('workforce_type', sa.String(), nullable=True))
    op.alter_column('projects', 'n_hours',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'n_hours',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('projects', 'workforce_type')
    # ### end Alembic commands ###
