"""added group_id for layers

Revision ID: 7088bacde47b
Revises: e96da8c54daa
Create Date: 2024-12-19 18:35:23.069643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '7088bacde47b'
down_revision: Union[str, None] = 'e96da8c54daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layers', sa.Column('destination', sa.String(), nullable=True))
    op.add_column('layers', sa.Column('destination_attr', sa.String(), nullable=True))
    op.add_column('layers', sa.Column('distance', sa.Integer(), nullable=True))
    op.add_column('layers', sa.Column('flow', sa.Integer(), nullable=True))
    op.add_column('layers', sa.Column('origin', sa.String(), nullable=True))
    op.add_column('layers', sa.Column('origin_attr', sa.String(), nullable=True))
    op.add_column('layers', sa.Column('population', sa.Integer(), nullable=True))
    op.add_column('layers', sa.Column('scaled_flows_forvis', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layers', 'scaled_flows_forvis')
    op.drop_column('layers', 'population')
    op.drop_column('layers', 'origin_attr')
    op.drop_column('layers', 'origin')
    op.drop_column('layers', 'flow')
    op.drop_column('layers', 'distance')
    op.drop_column('layers', 'destination_attr')
    op.drop_column('layers', 'destination')
    # ### end Alembic commands ###
