"""added specialists as a separate table related to project

Revision ID: 749ad811e27b
Revises: 8d3e713fdb77
Create Date: 2024-11-30 21:33:11.283288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '749ad811e27b'
down_revision: Union[str, None] = '8d3e713fdb77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'specialists', ['specialty'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'specialists', type_='unique')
    # ### end Alembic commands ###
