"""added group_id for layers

Revision ID: 7bb82e5cb57a
Revises: 1f8c12285d69
Create Date: 2024-12-19 16:24:21.905215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '7bb82e5cb57a'
down_revision: Union[str, None] = '1f8c12285d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layers', sa.Column('group_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layers', 'group_id')
    # ### end Alembic commands ###
