"""added specialists as a separate table related to project

Revision ID: 8c438d08645b
Revises: 9fe9737d7135
Create Date: 2024-11-30 23:44:09.168619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '8c438d08645b'
down_revision: Union[str, None] = '9fe9737d7135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'specialists', ['specialty'])
    op.drop_column('specialists', 'count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialists', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'specialists', type_='unique')
    # ### end Alembic commands ###
