"""added specialists as a separate table related to project

Revision ID: 8d3e713fdb77
Revises: 47f374e98453
Create Date: 2024-11-30 21:21:18.361619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '8d3e713fdb77'
down_revision: Union[str, None] = '47f374e98453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_specialists', sa.Column('count', sa.Integer(), nullable=False))
    op.drop_constraint('specialists_project_id_fkey', 'specialists', type_='foreignkey')
    op.drop_column('specialists', 'count')
    op.drop_column('specialists', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialists', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('specialists', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('specialists_project_id_fkey', 'specialists', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('project_specialists', 'count')
    # ### end Alembic commands ###
