"""added specialists as a separate table related to project

Revision ID: 952ec9462b32
Revises: d7bc8f7c870d
Create Date: 2024-11-30 21:41:55.519322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '952ec9462b32'
down_revision: Union[str, None] = 'd7bc8f7c870d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
