"""added salary

Revision ID: 964a5c761a89
Revises: ed4e9e10f5b0
Create Date: 2024-12-19 23:29:24.218200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '964a5c761a89'
down_revision: Union[str, None] = 'ed4e9e10f5b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layers', sa.Column('estimate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layers', 'estimate')
    # ### end Alembic commands ###
