"""added specialists as a separate table related to project

Revision ID: 9fe9737d7135
Revises: bc3db6dcfe2e
Create Date: 2024-11-30 23:33:36.829630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '9fe9737d7135'
down_revision: Union[str, None] = 'bc3db6dcfe2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('specialists_specialty_key', 'specialists', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('specialists_specialty_key', 'specialists', ['specialty'])
    # ### end Alembic commands ###
