"""added constraint to specialist schema

Revision ID: ab05e3f83ca2
Revises: 0f6c1069ff07
Create Date: 2024-12-01 23:07:40.791358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'ab05e3f83ca2'
down_revision: Union[str, None] = '0f6c1069ff07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_specialist_project', 'specialists', ['specialty', 'project_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_specialist_project', 'specialists', type_='unique')
    # ### end Alembic commands ###
