"""changed layer model

Revision ID: b00602d166b9
Revises: d583a0269580
Create Date: 2024-12-11 00:46:47.604708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b00602d166b9'
down_revision: Union[str, None] = 'd583a0269580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layers', sa.Column('fill_opacity', sa.Float(), nullable=True))
    op.add_column('layers', sa.Column('line_width', sa.Float(), nullable=True))
    op.add_column('layers', sa.Column('color', sa.String(), nullable=True))
    op.drop_column('layers', 'properties')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layers', sa.Column('properties', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('layers', 'color')
    op.drop_column('layers', 'line_width')
    op.drop_column('layers', 'fill_opacity')
    # ### end Alembic commands ###
