"""added a few more cols to proj

Revision ID: c6333ebf5357
Revises: 4323cd3a5b3a
Create Date: 2024-12-05 04:31:13.895963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'c6333ebf5357'
down_revision: Union[str, None] = '4323cd3a5b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('specialists_total', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('graduates_total', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('all_total', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'all_total')
    op.drop_column('projects', 'graduates_total')
    op.drop_column('projects', 'specialists_total')
    # ### end Alembic commands ###
