"""added group_id for layers

Revision ID: c64c137e5561
Revises: 7b9de38b115c
Create Date: 2024-12-19 21:10:37.724934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'c64c137e5561'
down_revision: Union[str, None] = '7b9de38b115c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layers', sa.Column('duration', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layers', 'duration')
    # ### end Alembic commands ###
