"""added specialists as a separate table related to project

Revision ID: d7bc8f7c870d
Revises: f04407a19071
Create Date: 2024-11-30 21:40:37.557293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'd7bc8f7c870d'
down_revision: Union[str, None] = 'f04407a19071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
