"""added specialists as a separate table related to project

Revision ID: e63722d6fedb
Revises: f38bfaaa6dd5
Create Date: 2024-12-01 00:06:14.314671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'e63722d6fedb'
down_revision: Union[str, None] = 'f38bfaaa6dd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
