"""added group_id for layers

Revision ID: f8e9a395b562
Revises: c64c137e5561
Create Date: 2024-12-19 22:32:12.191818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'f8e9a395b562'
down_revision: Union[str, None] = 'c64c137e5561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layers', sa.Column('in_diff', sa.Integer(), nullable=True))
    op.add_column('layers', sa.Column('out_diff', sa.Integer(), nullable=True))
    op.add_column('layers', sa.Column('in_out_diff', sa.Integer(), nullable=True))
    op.add_column('layers', sa.Column('ueqi_street_networks', sa.Integer(), nullable=True))
    
    # Explicitly cast `destination_attr` to Integer
    op.alter_column(
        'layers', 
        'destination_attr',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using="destination_attr::integer"  # Explicit casting
    )
    
    # Explicitly cast `origin_attr` to Integer
    op.alter_column(
        'layers', 
        'origin_attr',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using="origin_attr::integer"  # Explicit casting
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('layers', 'origin_attr',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('layers', 'destination_attr',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('layers', 'ueqi_street_networks')
    op.drop_column('layers', 'in_out_diff')
    op.drop_column('layers', 'out_diff')
    op.drop_column('layers', 'in_diff')
    # ### end Alembic commands ###
